// Generated by CoffeeScript 1.7.1
(function() {
  var module;

  module = angular.module('ngRouteFallback', ['ngRoute']);

  module.config(function($routeProvider) {
    var _when;
    _when = $routeProvider.when;
    return $routeProvider.when = function(route, args) {
      var check, target, _ref;
      if (args.fallback) {
        if (args.resolve == null) {
          args.resolve = {};
        }
        _ref = args.fallback;
        for (target in _ref) {
          check = _ref[target];
          if (args.fallback.hasOwnProperty(target)) {
            (function(target, check) {
              return args.resolve['_fallbackToCondition' + target] = function($q, $location, $injector) {
                var defer, result;
                defer = $q.defer();
                result = $injector.invoke(check);
                if (result && typeof result.then === 'function') {
                  result.then(function(deferredResult) {
                    var r, _i, _len;
                    if (angular.isArray(deferredResult)) {
                      for (_i = 0, _len = deferredResult.length; _i < _len; _i++) {
                        r = deferredResult[_i];
                        if (r) {
                          return $location.path(target);
                        }
                      }
                    } else {
                      if (deferredResult) {
                        return $location.path(target);
                      }
                    }
                    return defer.resolve();
                  }, function(failed) {
                    return $location.path(target);
                  });
                } else {
                  if (result) {
                    $location.path(target);
                  }
                  defer.resolve();
                }
                return defer.promise;
              };
            })(target, check);
          }
        }
      }
      return _when.call($routeProvider, route, args);
    };
  });

}).call(this);
